# -*- coding: utf-8 -*-
"""FEATURE SELECTION AND ENGINEERING.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2Uw-sUxi6iu-OmeodPQaW5vRTfpMQwS

#**4 FEATURE SELECTION AND ENGINEERING**
"""

# Segment drinks since 2012 by %
df2012 = df3.copy()
selected = ['year', 'region', 'wine-percentage', 'beer-percentage', 'vodka-percentage', 'champagne-percentage', 'brandy-percentage']
df2012 = df2012[df2012.year>2011][selected]
df2012 = df2012.groupby('region').mean().drop(columns='year')

# Segment wine avg and share since 2012
wine2010 = df3.copy()
wine2010 = wine2010[wine2010.year>2009]
wine_ewm = wine2010[['year', 'region', 'wine']]
wine2010 = wine2010[['year','region','wine','wine-percentage']]
wine2010 = wine2010.groupby('region').mean().drop(columns='year')
wine2010.rename(columns = {"wine": "wine7avg",
                         'wine-percentage': 'wine7%'}, 
                    inplace = True)

# Segment wine exponentially weighted avg since 2012
wine_ewm = wine_ewm.groupby('region')
wine_ewm = wine_ewm.apply(lambda x: x.ewm(span=7).mean().iloc[-1]).drop(columns='year')
wine_ewm.rename(columns = {"wine": "wine7ewm"}, 
                    inplace = True)

wine_section = pd.merge(wine2010, wine_ewm, on='region')
# Final df
df_final = pd.merge(wine_section, df2012, on='region')